apiVersion: v1
kind: Secret
metadata:
  name: ui-creds
type: Opaque
data:
  # Must be base64 encoded - e.g. echo -n 'some_username' | base64
  username: some_username
  password: some_password
  recipient: some_recipient