apiVersion: apps/v1
kind: Deployment
metadata:
  name: &Name ui-deployment
spec:
  selector:
    matchLabels:
      app: *Name
  replicas: 1
  template:
    metadata:
      labels:
        app: *Name
    spec:
      containers:
        - name: ui-deployment-container
          image: samhumphreys/code:4809e4376005003f9044882a147ce9da9dd0998a
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: ui-creds
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ui-creds
                  key: password
            - name: RECIPIENT
              valueFrom:
                secretKeyRef:
                  name: ui-creds
                  key: recipient
          # Deploy with gunicorn due to Flask server intended only for development
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "code.ui:app"]
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - name: http
              containerPort: 5000
      volumes:
        - name: ui-creds
          secret:
            secretName: ui-creds